apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: web-components
  labels:
    app: gateway
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      namespace: web-components
      version: blue
  template:
    metadata:
      labels:
        app: gateway
        namespace: web-components
        version: blue
    spec:
      containers:
      - name: gateway
        image: diskit/gateway
        env:
        - name: KONG_DECLARATIVE_CONFIG
          value: "/etc/kong-nginx/kong.yml"
        - name: KONG_DATABASE
          value: "off"
        imagePullPolicy: Never
        volumeMounts:
        - name: config
          mountPath: "/etc/kong-nginx"
          readOnly: true
        ports:
        - containerPort: 8080
      volumes:
      - name: config
        configMap:
          name: gateway-config

