apiVersion: v1
metadata:
  name: gateway-svc
  namespace: web-components
kind: Service
spec:
  ports:
  - name: gateway-svc
    protocol: TCP
    port: 8000
    targetPort: 8000
  type: NodePort
  selector:
    app: gateway
