apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: auth-api
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: diskit/auth-api
    context: .
    docker:
      dockerfile: docker/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
