apiVersion: v1
metadata:
  name: user-api-svc
  namespace: web-components
kind: Service
spec:
  ports:
  - name: user-api-svc
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
  selector:
    app: user-api
