_format_version: "1.1"

services:
- name: app
  url: http://host.docker.internal:8081
  routes:
  - name: app
    paths:
    - /
- name: api
  url: http://host.docker.internal:8082
  plugins:
  - name: access-control
  routes:
  - name: api
    paths:
    - /api
- name: auth
  url: http://host.docker.internal:8083
  routes:
  - name: auth
    paths:
    - /auth
- name: scripts
  url: http://host.docker.internal:8084
  plugins:
  - name: token-upgrader
  routes:
  - name: scripts
    paths:
    - /scripts