apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: gateway
build:
  local:
    push: false
    useBuildkit: true
    useDockerCLI: true
  artifacts:
  - image: diskit/gateway
    context: .
    docker:
      dockerfile: docker/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/configmap.yaml
    - k8s/deployment.yaml
    - k8s/service.yaml
