apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: user-api
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
  - image: diskit/user-api
    context: .
    docker:
      dockerfile: docker/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
    - k8s/configmap.yaml
portForward:
  - resourceType: Service
    resourceName: user-api-svc
    namespace: web-components
    port: 8080
    localPort: 18082