apiVersion: apps/v1
kind: Deployment
metadata:
  name: components
  namespace: web-components
  labels:
    app: components
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: components
      namespace: web-components
      version: blue
  template:
    metadata:
      labels:
        app: components
        namespace: web-components
        version: blue
    spec:
      containers:
      - name: components
        image: diskit/components
        imagePullPolicy: Never
        ports:
        - containerPort: 80

