apiVersion: v1
metadata:
  name: components-svc
  namespace: web-components
kind: Service
spec:
  ports:
  - name: components-svc
    protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
  selector:
    app: components
