apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff
  namespace: web-components
  labels:
    app: bff
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff
      namespace: web-components
      version: blue
  template:
    metadata:
      labels: 
        app: bff
        namespace: web-components
        version: blue
    spec:
      containers:
      - name: nginx
        image: diskit/bff
        imagePullPolicy: Never
        ports:
        - containerPort: 8080