apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: web-components
build:
  local:
    push: false
  artifacts:
  - image: diskit/components
    context: .
    docker:
      dockerfile: docker/Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml